---
- name: Delete classic sources.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: Install mirror definition
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list.d/mirror.list
