---
- name: Set baseurl in repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.0.file }}
    section: "{{ item.1 }}"
    option: baseurl
    value: "{{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] }}/$releasever/{{ item.1}}/$basearch/"
  with_subelements:
    - - file: CentOS-Base.repo
        sections:
          - base
          - updates
          - extras
          - centosplus
      - file: CentOS-CR.repo
        sections:
          - cr
      - file: CentOS-fasttrack.repo
        sections:
          - fasttrack
    - sections
