---
- name: Include var loading tasks for {{ ansible_distribution }}
  include_tasks: vars-{{ ansible_distribution | lower }}.yml

- name: Include shared tasks for YUM and DNF
  include_tasks: yum-dnf-shared.yml
