---
- name: Include var loading tasks for {{ ansible_distribution }}
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Include shared tasks for YUM and DNF
  include_tasks: shared/yum-repos.yml
