---
- name: Load variables for Scientific {{ ansible_distribution_major_version }}
  include_vars:
    file: scientific{{ ansible_distribution_major_version }}.yml

- name: Remove lines non-compliant with INI format
  lineinfile:
    regexp: "^[^[=]+$"
    state: absent
    dest: /etc/yum.repos.d/{{ item }}
  with_items: "{{ pkgmgr_sl_sections | map(attribute = 'file') | unique | list }}"

- name: Configure baseurl in stock repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.file }}
    section: "{{ item.section }}"
    option: baseurl
    value: "{{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] }}{{ item.uri }}"
  with_items: "{{ pkgmgr_sl_sections }}"

- name: Remove non-compliant lines from optional repos
  lineinfile:
    regexp: "^[^[=]+$"
    state: absent
    dest: /etc/yum.repos.d/{{ item }}
  with_items: "{{ pkgmgr_sl_optional | map(attribute = 'file') | unique | list }}"
  when: pkgmgr_sl_optional is defined

- name: Configure baseurl in optional repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.file }}
    create: false
    section: "{{ item.section }}"
    option: baseurl
    value: "{{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] }}{{ item.uri }}"
  with_items: "{{ pkgmgr_sl_optional }}"
  when: pkgmgr_sl_optional is defined
  ignore_errors: true
