---
- name: Load variables for Scientific {{ ansible_distribution_major_version }}
  include_vars:
    file: scientific{{ ansible_distribution_major_version }}.yml

# Regex explanation: find non-empty lines until EOL or comment (marked by "#" or ";") entirely
# consisting of characters other than "=" and "[". In other words, find non-empty, non-comment
# lines that are neither section names nor "option = value" pairs.
- name: Find files not conforming to INI format
  command: >
    grep -l '^[^#=[]\+\($\|[#;]\)'
    {{ pkgmgr_sl_sections | map(attribute = 'file') | unique | map('quote') | join(' ') }}
  args:
    chdir: /etc/yum.repos.d
  register: pkgmgr_grep_result
  changed_when: false
  failed_when: pkgmgr_grep_result.rc > 2

# Script explanation
# FIRST LINE:
# - save to hold space
# - delete
# "CROOKED" LINES:
# - append pattern space to hold space
# - if last line:
#   - swap hold and pattern space
#   - unfold
#   else:
#   - delete
# "NORMAL" LINES:
# - swap hold and pattern space
# - unfold
# - if last line:
#   - append hold space to pattern space
- name: Unfold lines in INI files
  command: >
    sed -i
    '1 { h; d; };
    /^[^#=[]\+\($\|[#;]\)/ {
    H;
    $ { x; s/[[:space:]]\+/ /g; };
    $! d;
    };
    /^[^#=[]\+\($\|[#;]\)/! {
    x;
    s/[[:space:]]\+/ /g;
    $ G;
    };'
    {{ pkgmgr_grep_result.stdout_lines | map('quote') | join(' ') }}
  when: pkgmgr_grep_result.rc == 0
  args:
    chdir: /etc/yum.repos.d
    warn: false

- name: Configure baseurl in stock repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.file }}
    section: "{{ item.section }}"
    option: baseurl
    value: "{{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] }}{{ item.uri }}"
  with_items: "{{ pkgmgr_sl_sections }}"

- name: Remove non-compliant lines from optional repos
  lineinfile:
    regexp: "^[^[=]+$"
    state: absent
    dest: /etc/yum.repos.d/{{ item }}
  with_items: "{{ pkgmgr_sl_optional | map(attribute = 'file') | unique | list }}"
  when: pkgmgr_sl_optional is defined

- name: Configure baseurl in optional repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.file }}
    create: false
    section: "{{ item.section }}"
    option: baseurl
    value: "{{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] }}{{ item.uri }}"
  with_items: "{{ pkgmgr_sl_optional }}"
  when: pkgmgr_sl_optional is defined
  ignore_errors: true
