---
- name: Include tasks for {{ ansible_distribution }}
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Configure YUM proxy
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ pkgmgr_proxy }}"
  when: pkgmgr_proxy is defined
