---
# Regex explanation: find non-empty lines until EOL or comment (marked by "#" or ";") entirely
# consisting of characters other than "=" and "[". In other words, find non-empty, non-comment
# lines that are neither section names nor "option = value" pairs.
- name: Find repos not conforming to INI format
  command: >
    grep -l '^[^#=[]\+\($\|[#;]\)'
    {{ pkgmgr_repos | map(attribute = 'file') | map('quote') | join(' ') }}
  args:
    chdir: /etc/yum.repos.d
  register: grep_result
  changed_when: false
  failed_when: grep_result.rc > 2
  check_mode: false

# Script explanation
# FIRST LINE:
# - save to hold space
# - delete
# "CROOKED" LINES:
# - append pattern space to hold space
# - if last line:
#   - swap hold and pattern space
#   - unfold
#   else:
#   - delete
# "NORMAL" LINES:
# - swap hold and pattern space
# - unfold
# - if last line:
#   - append hold space to pattern space
- name: Unfold lines in repos
  command: >-
    sed -i
    '1 { h; d; };
    /^[^#=[]\+\($\|[#;]\)/ {
    H;
    $ { x; s/[[:space:]]\+/ /g; };
    $! d;
    };
    /^[^#=[]\+\($\|[#;]\)/! {
    x;
    s/[[:space:]]\+/ /g;
    $ G;
    };'
    {{ grep_result.stdout_lines | map('quote') | join(' ') }}
  when: not ansible_check_mode and grep_result.rc == 0
  args:
    chdir: /etc/yum.repos.d
    warn: false

# Use ini_file, not yum_repository, as it doesn't require description and other data
- name: Configure baseurl in repos
  ini_file:
    dest: /etc/yum.repos.d/{{ item.file }}
    section: "{{ item.name }}"
    option: baseurl
    value: >-
      {{ pkgmgr_mirror[ansible_distribution]['v' + ansible_distribution_major_version] |
      default(pkgmgr_mirror[ansible_distribution]['default']) }}{{ item.uri }}
  with_items: "{{ pkgmgr_repos }}"

- name: Disable metalinks and mirror lists
  ini_file:
    dest: /etc/yum.repos.d/{{ item.0.file }}
    section: "{{ item.0.name }}"
    option: "{{ item.1 }}"
    state: absent
  with_nested:
    - "{{ pkgmgr_repos }}"
    - [ metalink, mirrorlist ]

- name: Configure proxy in {{ ansible_pkg_mgr | upper }}
  ini_file:
    dest: "{{ ( ansible_pkg_mgr == 'dnf') | ternary('/etc/dnf/dnf.conf', '/etc/yum.conf') }}"
    section: main
    option: proxy
    value: "{{ pkgmgr_proxy }}"
  when: pkgmgr_proxy is defined
